name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Format
    uses: PhilNel/shared-go-workflows/.github/workflows/lint.yml@main

  test:
    name: Run Tests
    uses: PhilNel/shared-go-workflows/.github/workflows/test.yml@main

  build:
    name: Build Binary
    needs: [lint]
    uses: PhilNel/shared-go-workflows/.github/workflows/build.yml@main
